#!/bin/bash
# One-time Sparkle auto-update setup for Omnibus.
#
# Run this yourself in Terminal on your Mac (it needs real macOS -- Sparkle's
# key tool talks to Keychain, and repo creation needs your own GitHub login,
# neither of which Claude can do on your behalf):
#
#   chmod +x scripts/setup-autoupdate.sh
#   ./scripts/setup-autoupdate.sh
#
# What it does:
#   1. Downloads Sparkle's generate_keys/sign_update command-line tools.
#   2. Generates (or reuses) your signing keypair. The PRIVATE key is
#      generated by Sparkle straight into your Mac's Keychain and this
#      script never touches, prints, exports, or commits it anywhere --
#      only the PUBLIC key (safe to publish) is ever written to a file.
#   3. Patches the SUPublicEDKey placeholder in project.yml and
#      App/Info.plist with that public key.
#   4. Creates a GitHub repo (via `gh`, if it's installed and logged in)
#      and pushes this project to it, then patches the SUFeedURL
#      placeholder to point at it.
#   5. Regenerates the Xcode project (`xcodegen generate`) if that's
#      installed too.
#
# Safe to re-run: generate_keys reuses an existing key instead of making a
# new one, and `gh repo create` / `xcodegen generate` are both idempotent
# for an already-set-up repo.

set -euo pipefail
cd "$(dirname "$0")/.."

REPO_NAME="${1:-Omnibus}"
TOOLS_DIR=".sparkle-tools"

step() { printf '\n\033[1m==> %s\033[0m\n' "$1"; }
die() { printf '\nERROR: %s\n' "$1" >&2; exit 1; }

# ---------------------------------------------------------------------------
step "Checking prerequisites"
# ---------------------------------------------------------------------------
command -v git >/dev/null || die "git is required (install Xcode Command Line Tools)."
command -v curl >/dev/null || die "curl is required."
command -v tar >/dev/null || die "tar is required."

HAVE_GH=0
if command -v gh >/dev/null && gh auth status >/dev/null 2>&1; then
    HAVE_GH=1
    echo "GitHub CLI found and logged in -- will create/push the repo for you."
else
    echo "GitHub CLI not found or not logged in (\`gh auth login\`) -- will skip"
    echo "repo creation and push; you'll do that part by hand (see AUTOUPDATE.md)."
fi

HAVE_XCODEGEN=0
if command -v xcodegen >/dev/null; then
    HAVE_XCODEGEN=1
fi

# ---------------------------------------------------------------------------
step "Fetching Sparkle's generate_keys / sign_update tools"
# ---------------------------------------------------------------------------
if [ -x "$TOOLS_DIR/bin/generate_keys" ]; then
    echo "Already downloaded, reusing $TOOLS_DIR."
else
    mkdir -p "$TOOLS_DIR"
    ASSET_URL=$(curl -sL https://api.github.com/repos/sparkle-project/Sparkle/releases/latest \
        | grep '"browser_download_url"' \
        | grep -v 'for-Swift-Package-Manager' \
        | grep -o 'https://[^"]*\.tar\.xz' \
        | head -n1)
    [ -n "$ASSET_URL" ] || die "Couldn't find a Sparkle release download -- check https://github.com/sparkle-project/Sparkle/releases manually."
    echo "Downloading $ASSET_URL"
    curl -sL "$ASSET_URL" -o "$TOOLS_DIR/sparkle.tar.xz"
    tar -xJf "$TOOLS_DIR/sparkle.tar.xz" -C "$TOOLS_DIR"
    rm -f "$TOOLS_DIR/sparkle.tar.xz"
    [ -x "$TOOLS_DIR/bin/generate_keys" ] || die "generate_keys not found after extracting -- Sparkle's release layout may have changed; see AUTOUPDATE.md for the manual steps."
fi

# ---------------------------------------------------------------------------
step "Generating (or reusing) your signing key"
# ---------------------------------------------------------------------------
# generate_keys prints the PUBLIC key to stdout and stores the PRIVATE key
# directly in Keychain -- it never writes the private key to disk, and
# neither does this script. If a key already exists it reuses it instead
# of making a new one.
KEYGEN_OUTPUT=$("$TOOLS_DIR/bin/generate_keys" 2>&1) || die "generate_keys failed:
$KEYGEN_OUTPUT"
echo "$KEYGEN_OUTPUT"

PUBLIC_KEY=$(echo "$KEYGEN_OUTPUT" | grep -oE '[A-Za-z0-9+/]{40,}={0,2}' | head -n1)
[ -n "$PUBLIC_KEY" ] || die "Couldn't parse a public key out of generate_keys' output (shown above) -- copy it manually into project.yml / App/Info.plist's SUPublicEDKey."
echo "Public key: $PUBLIC_KEY"

# ---------------------------------------------------------------------------
step "Creating and pushing the GitHub repo"
# ---------------------------------------------------------------------------
GITHUB_USERNAME=""
if [ "$HAVE_GH" = "1" ]; then
    GITHUB_USERNAME=$(gh api user -q .login)
    if gh repo view "$GITHUB_USERNAME/$REPO_NAME" >/dev/null 2>&1; then
        echo "Repo $GITHUB_USERNAME/$REPO_NAME already exists, skipping creation."
        git remote get-url origin >/dev/null 2>&1 || git remote add origin "https://github.com/$GITHUB_USERNAME/$REPO_NAME.git"
    else
        gh repo create "$REPO_NAME" --public \
            --description "Personal Classroom/Chat/SchoolSoft dashboard" \
            --source=. --remote=origin
    fi
else
    read -rp "GitHub username (for the SUFeedURL placeholder -- won't create/push anything): " GITHUB_USERNAME
fi

# ---------------------------------------------------------------------------
step "Patching placeholders in project.yml and App/Info.plist"
# ---------------------------------------------------------------------------
for FILE in project.yml App/Info.plist; do
    sed -i '' "s|REPLACE_WITH_YOUR_SPARKLE_PUBLIC_KEY|$PUBLIC_KEY|g" "$FILE"
    sed -i '' "s|YOUR_GITHUB_USERNAME|$GITHUB_USERNAME|g" "$FILE"
    sed -i '' "s|/Omnibus/main/appcast.xml|/$REPO_NAME/main/appcast.xml|g" "$FILE"
done
sed -i '' "s|YOUR_GITHUB_USERNAME|$GITHUB_USERNAME|g" appcast.xml
sed -i '' "s|/Omnibus/main/appcast.xml|/$REPO_NAME/main/appcast.xml|g" appcast.xml
echo "Patched."

# ---------------------------------------------------------------------------
step "Regenerating the Xcode project"
# ---------------------------------------------------------------------------
if [ "$HAVE_XCODEGEN" = "1" ]; then
    xcodegen generate
else
    echo "xcodegen not found -- install it (brew install xcodegen) and run"
    echo "\`xcodegen generate\` yourself before building."
fi

# ---------------------------------------------------------------------------
step "Committing the changes"
# ---------------------------------------------------------------------------
git add -A
if git diff --cached --quiet; then
    echo "Nothing to commit."
else
    git commit -m "Configure Sparkle auto-update"
    if [ "$HAVE_GH" = "1" ]; then
        git push -u origin main
    fi
fi

step "Done"
cat <<SUMMARY

Public key : $PUBLIC_KEY
Feed URL   : https://raw.githubusercontent.com/$GITHUB_USERNAME/$REPO_NAME/main/appcast.xml
Repo       : $([ "$HAVE_GH" = "1" ] && echo "https://github.com/$GITHUB_USERNAME/$REPO_NAME (created & pushed)" || echo "not created -- do this by hand, see AUTOUPDATE.md")

The private signing key never left your Keychain and was never written to
a file or committed anywhere -- that's intentional, it must stay secret.
Open Keychain Access and search "sparkle" if you ever want to back it up
(e.g. before wiping this Mac); without it, you won't be able to sign
future updates and existing installs won't be able to verify them.

Next: open the project in Xcode and build once so it resolves the Sparkle
package. Then see AUTOUPDATE.md section 5 for the release routine (this
script only did the one-time setup, not shipping an actual update).
SUMMARY
